#!/usr/bin/env python3
"""Generate the TypeScript beat-sheet registry from src/beats/*.json."""

from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path

DEFAULT_ENGINE = Path(__file__).resolve().parent.parent  # repo root


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--engine",
        type=Path,
        default=Path(os.environ.get("REEL_ENGINE", DEFAULT_ENGINE)),
    )
    args = parser.parse_args()
    engine = args.engine.expanduser().resolve()
    beat_dir = engine / "src/beats"
    if not beat_dir.exists():
        raise SystemExit(f"missing beat directory: {beat_dir}")

    entries: list[tuple[str, str]] = []
    # id -> the file that claimed it, so a collision can name BOTH sides.
    seen: dict[str, Path] = {}
    for path in sorted(beat_dir.glob("*.json")):
        data = json.loads(path.read_text())
        reel_id = data.get("id")
        if not isinstance(reel_id, str) or not re.fullmatch(r"[A-Za-z0-9-]+", reel_id):
            raise SystemExit(f"invalid composition id in {path}: {reel_id!r}")
        if reel_id in seen:
            # NAME BOTH FILES. This used to say only "duplicate composition id:
            # <id>", which is the id you already know and not the two files you
            # need. It cost a render cycle on 2026-08-19: tools/pace_reel.py had
            # written its backup to src/beats/<slug>.orig.json, every *.json here
            # is registered as a composition, and the message gave no way to see
            # that without going and looking. The machine failed in 0.02s; the
            # diagnosis is what took the time.
            first, second = seen[reel_id], path
            hint = ""
            if any(m in second.name for m in (".orig", ".bak", ".backup", "copy", "-old")):
                hint = (f"\n  {second.name} looks like a BACKUP. Every *.json in "
                        f"src/beats/ is registered as a composition, so a backup "
                        f"kept here becomes a second reel with the same id. Move "
                        f"it outside src/beats/ (out/ is fine).")
            raise SystemExit(
                f"duplicate composition id {reel_id!r}, claimed by two files:\n"
                f"  {first}\n  {second}{hint}")
        seen[reel_id] = path
        entries.append((path.stem, reel_id))

    lines = [
        "/* Auto-generated by scripts/register_beats.py. */",
        'import type { BeatSheet } from "./types";',
    ]
    for index, (stem, _) in enumerate(entries):
        lines.append(f'import sheet{index} from "./beats/{stem}.json";')
    lines.extend(
        [
            "",
            "export const beatSheets = [",
            *[f"  sheet{index}," for index in range(len(entries))],
            "] as unknown as BeatSheet[];",
            "",
        ]
    )
    output = engine / "src/generatedBeatSheets.ts"
    content = "\n".join(lines)
    if output.exists() and output.read_text() == content:
        print(f"registry already current: {output}")
        return
    output.write_text(content)
    print(f"registered {len(entries)} beat sheets: {output}")


if __name__ == "__main__":
    main()
