#!/usr/bin/env python3
"""Generate the TypeScript beat-sheet registry from src/beats/*.json."""

from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path

DEFAULT_ENGINE = Path(__file__).resolve().parent.parent  # repo root


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--engine",
        type=Path,
        default=Path(os.environ.get("REEL_ENGINE", DEFAULT_ENGINE)),
    )
    args = parser.parse_args()
    engine = args.engine.expanduser().resolve()
    beat_dir = engine / "src/beats"
    if not beat_dir.exists():
        raise SystemExit(f"missing beat directory: {beat_dir}")

    entries: list[tuple[str, str]] = []
    seen: set[str] = set()
    for path in sorted(beat_dir.glob("*.json")):
        data = json.loads(path.read_text())
        reel_id = data.get("id")
        if not isinstance(reel_id, str) or not re.fullmatch(r"[A-Za-z0-9-]+", reel_id):
            raise SystemExit(f"invalid composition id in {path}: {reel_id!r}")
        if reel_id in seen:
            raise SystemExit(f"duplicate composition id: {reel_id}")
        seen.add(reel_id)
        entries.append((path.stem, reel_id))

    lines = [
        "/* Auto-generated by scripts/register_beats.py. */",
        'import type { BeatSheet } from "./types";',
    ]
    for index, (stem, _) in enumerate(entries):
        lines.append(f'import sheet{index} from "./beats/{stem}.json";')
    lines.extend(
        [
            "",
            "export const beatSheets = [",
            *[f"  sheet{index}," for index in range(len(entries))],
            "] as unknown as BeatSheet[];",
            "",
        ]
    )
    output = engine / "src/generatedBeatSheets.ts"
    content = "\n".join(lines)
    if output.exists() and output.read_text() == content:
        print(f"registry already current: {output}")
        return
    output.write_text(content)
    print(f"registered {len(entries)} beat sheets: {output}")


if __name__ == "__main__":
    main()
