/* Auto-generated by scripts/register_beats.py. */
import type { BeatSheet } from "./types";
import sheet0 from "./beats/10-ai-tools-free-vs-paid.json";
import sheet1 from "./beats/airpods-camera.json";
import sheet2 from "./beats/apple-pay-india.json";
import sheet3 from "./beats/apple-pencil-iphone-ultra.json";
import sheet4 from "./beats/apple-reference-image.json";
import sheet5 from "./beats/apple-surprise-and-shine.json";
import sheet6 from "./beats/chatgpt-photo-prompts.json";
import sheet7 from "./beats/chatgpt-stickers.json";
import sheet8 from "./beats/claude-eating-tokens.json";
import sheet9 from "./beats/claude-fable-5-1.json";
import sheet10 from "./beats/claude-memory-everywhere.json";
import sheet11 from "./beats/five-free-ai-tools.json";
import sheet12 from "./beats/grok-bot.json";
import sheet13 from "./beats/ios-27-2-beta-1.json";
import sheet14 from "./beats/ios-27-beta-8.json";
import sheet15 from "./beats/ios27-battery-drain.json";
import sheet16 from "./beats/ios27-beta7.json";
import sheet17 from "./beats/ios27-tiers-nomusic.json";
import sheet18 from "./beats/ios27-tiers.json";
import sheet19 from "./beats/iphone-18-pro-nomusic.json";
import sheet20 from "./beats/iphone-18-pro.json";
import sheet21 from "./beats/iphone-fold-ultra-nomusic.json";
import sheet22 from "./beats/iphone-fold-ultra.json";
import sheet23 from "./beats/iphone-third-interface.json";
import sheet24 from "./beats/iphone18-colors-nomusic.json";
import sheet25 from "./beats/iphone18-colors.json";
import sheet26 from "./beats/iphone18-split.json";
import sheet27 from "./beats/mac-mini-m6-m5pro.json";
import sheet28 from "./beats/mac-multiple-headphones.json";
import sheet29 from "./beats/made-by-google-26.json";
import sheet30 from "./beats/qualcomm-chip-hike.json";
import sheet31 from "./beats/seedance-25.json";
import sheet32 from "./beats/september-preview-nomusic.json";
import sheet33 from "./beats/september-preview.json";
import sheet34 from "./beats/whatsapp-agents.json";

export const beatSheets = [
  sheet0,
  sheet1,
  sheet2,
  sheet3,
  sheet4,
  sheet5,
  sheet6,
  sheet7,
  sheet8,
  sheet9,
  sheet10,
  sheet11,
  sheet12,
  sheet13,
  sheet14,
  sheet15,
  sheet16,
  sheet17,
  sheet18,
  sheet19,
  sheet20,
  sheet21,
  sheet22,
  sheet23,
  sheet24,
  sheet25,
  sheet26,
  sheet27,
  sheet28,
  sheet29,
  sheet30,
  sheet31,
  sheet32,
  sheet33,
  sheet34,
] as unknown as BeatSheet[];
