/* Auto-generated by scripts/register_beats.py. */
import type { BeatSheet } from "./types";
import sheet0 from "./beats/airpods-camera.json";
import sheet1 from "./beats/apple-pay-india.json";
import sheet2 from "./beats/apple-surprise-and-shine.json";
import sheet3 from "./beats/claude-eating-tokens.json";
import sheet4 from "./beats/grok-bot.json";
import sheet5 from "./beats/ios27-beta7.json";
import sheet6 from "./beats/ios27-tiers-nomusic.json";
import sheet7 from "./beats/ios27-tiers.json";
import sheet8 from "./beats/iphone-18-pro-nomusic.json";
import sheet9 from "./beats/iphone-18-pro.json";
import sheet10 from "./beats/iphone-fold-ultra-nomusic.json";
import sheet11 from "./beats/iphone-fold-ultra.json";
import sheet12 from "./beats/iphone-third-interface.json";
import sheet13 from "./beats/iphone18-colors-nomusic.json";
import sheet14 from "./beats/iphone18-colors.json";
import sheet15 from "./beats/iphone18-split.json";
import sheet16 from "./beats/mac-mini-m6-m5pro.json";
import sheet17 from "./beats/made-by-google-26.json";
import sheet18 from "./beats/seedance-25.json";
import sheet19 from "./beats/september-preview-nomusic.json";
import sheet20 from "./beats/september-preview.json";

export const beatSheets = [
  sheet0,
  sheet1,
  sheet2,
  sheet3,
  sheet4,
  sheet5,
  sheet6,
  sheet7,
  sheet8,
  sheet9,
  sheet10,
  sheet11,
  sheet12,
  sheet13,
  sheet14,
  sheet15,
  sheet16,
  sheet17,
  sheet18,
  sheet19,
  sheet20,
] as unknown as BeatSheet[];
